// Strait design tokens v2 — GENERATED by brand/tokens/build.mjs from strait.tokens.json. Do not edit.
export const colors = {
  "light": {
    "bg": "#FFFFFF",
    "bg-subtle": "#FAF8F6",
    "bg-muted": "#F3EFEB",
    "surface": "#FFFFFF",
    "surface-raised": "#FFFFFF",
    "border": "#E7E0D9",
    "border-strong": "#CFC5BC",
    "border-control": "#948779",
    "text": "#1C1410",
    "text-muted": "#5B4F47",
    "text-subtle": "#76695F",
    "text-inverse": "#FFFFFF",
    "brand": "#F47A1F",
    "brand-hover": "#FA8E3A",
    "brand-press": "#D9620F",
    "on-brand": "#1C1410",
    "brand-subtle": "#FFF5EC",
    "brand-border": "#FFCFA6",
    "brand-text": "#B04C0C",
    "link": "#B04C0C",
    "link-hover": "#8C3D10",
    "focus-ring": "#D9620F",
    "accent": "#FF5A1F",
    "accent-text": "#B8360F",
    "success": "#15803D",
    "success-bg": "#ECFDF3",
    "warning": "#A35208",
    "warning-bg": "#FFF7E8",
    "danger": "#B91C1C",
    "danger-bg": "#FEF2F2",
    "info": "#1D4ED8",
    "info-bg": "#EFF6FF",
    "chart-1": "#F47A1F",
    "chart-2": "#2F6FED",
    "chart-3": "#0F9F8F",
    "chart-4": "#8B5CF6",
    "chart-5": "#E0457B",
    "chart-6": "#6B7A8C"
  },
  "dark": {
    "bg": "#121010",
    "bg-subtle": "#191614",
    "bg-muted": "#2A2420",
    "surface": "#1F1B18",
    "surface-raised": "#26211D",
    "border": "#362F2A",
    "border-strong": "#4B423B",
    "border-control": "#7C6F65",
    "text": "#F6F1EC",
    "text-muted": "#B9AEA5",
    "text-subtle": "#988C83",
    "text-inverse": "#121010",
    "brand": "#F47A1F",
    "brand-hover": "#FA8E3A",
    "brand-press": "#D9620F",
    "on-brand": "#121010",
    "brand-subtle": "#2B1B10",
    "brand-border": "#5A3315",
    "brand-text": "#FA8E3A",
    "link": "#FA8E3A",
    "link-hover": "#FFAE6D",
    "focus-ring": "#FA8E3A",
    "accent": "#FF7A45",
    "accent-text": "#FF7A45",
    "success": "#4ADE80",
    "success-bg": "#14271B",
    "warning": "#F5B547",
    "warning-bg": "#2B2010",
    "danger": "#F87171",
    "danger-bg": "#2D1515",
    "info": "#7AB2FF",
    "info-bg": "#14203A",
    "chart-1": "#FA8E3A",
    "chart-2": "#6EA0FF",
    "chart-3": "#2DD4BF",
    "chart-4": "#A78BFA",
    "chart-5": "#F472B6",
    "chart-6": "#94A3B8"
  }
} as const;
export type ColorToken = keyof typeof colors.light;
export const primitives = {
  "orange": {
    "50": "#FFF5EC",
    "100": "#FFE8D3",
    "200": "#FFCFA6",
    "300": "#FFAE6D",
    "400": "#FA8E3A",
    "500": "#F47A1F",
    "600": "#D9620F",
    "700": "#B04C0C",
    "800": "#8C3D10",
    "900": "#723312",
    "950": "#3F1806"
  },
  "ember": {
    "400": "#FF7A45",
    "500": "#FF5A1F",
    "600": "#E04412",
    "700": "#B8360F"
  },
  "neutral": {
    "0": "#FFFFFF",
    "25": "#FAF8F6",
    "50": "#F3EFEB",
    "100": "#E7E0D9",
    "200": "#CFC5BC",
    "300": "#B3A79D",
    "400": "#948779",
    "500": "#76695F",
    "600": "#5B4F47",
    "700": "#4B423B",
    "750": "#7C6F65",
    "800": "#362F2A",
    "850": "#2A2420",
    "875": "#26211D",
    "900": "#1F1B18",
    "925": "#191614",
    "950": "#1C1410",
    "1000": "#121010"
  }
} as const;
export const space = {"0":0,"1":4,"2":8,"3":12,"4":16,"5":20,"6":24,"8":32,"10":40,"12":48,"16":64,"24":96} as const;
export const radius = {"xs":4,"sm":6,"md":8,"lg":12,"xl":16,"full":999} as const;
export const fonts = {
  "display": "Geist, Inter, 'Helvetica Neue', Arial, sans-serif",
  "body": "Inter, system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif",
  "mono": "'JetBrains Mono', 'SF Mono', Menlo, Consolas, monospace"
} as const;
export const text = {
  "display-xl": {
    "family": "display",
    "fontSize": 56,
    "lineHeight": 60,
    "fontWeight": "600",
    "letterSpacing": "-0.03em"
  },
  "display-lg": {
    "family": "display",
    "fontSize": 44,
    "lineHeight": 48,
    "fontWeight": "600",
    "letterSpacing": "-0.025em"
  },
  "h1": {
    "family": "display",
    "fontSize": 32,
    "lineHeight": 38,
    "fontWeight": "600",
    "letterSpacing": "-0.02em"
  },
  "h2": {
    "family": "display",
    "fontSize": 24,
    "lineHeight": 30,
    "fontWeight": "600",
    "letterSpacing": "-0.015em"
  },
  "h3": {
    "family": "display",
    "fontSize": 19,
    "lineHeight": 26,
    "fontWeight": "600",
    "letterSpacing": "-0.01em"
  },
  "h4": {
    "family": "body",
    "fontSize": 15,
    "lineHeight": 22,
    "fontWeight": "600",
    "letterSpacing": "0"
  },
  "body-lg": {
    "family": "body",
    "fontSize": 17,
    "lineHeight": 27,
    "fontWeight": "400",
    "letterSpacing": "0"
  },
  "body": {
    "family": "body",
    "fontSize": 14,
    "lineHeight": 21,
    "fontWeight": "400",
    "letterSpacing": "0"
  },
  "body-sm": {
    "family": "body",
    "fontSize": 13,
    "lineHeight": 19,
    "fontWeight": "400",
    "letterSpacing": "0"
  },
  "caption": {
    "family": "body",
    "fontSize": 12,
    "lineHeight": 16,
    "fontWeight": "500",
    "letterSpacing": "0.01em"
  },
  "overline": {
    "family": "mono",
    "fontSize": 11,
    "lineHeight": 14,
    "fontWeight": "500",
    "letterSpacing": "0.08em"
  },
  "code": {
    "family": "mono",
    "fontSize": 13,
    "lineHeight": 20,
    "fontWeight": "400",
    "letterSpacing": "0"
  },
  "metric": {
    "family": "display",
    "fontSize": 28,
    "lineHeight": 32,
    "fontWeight": "600",
    "letterSpacing": "-0.02em"
  }
} as const;
